/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/bg.glb --t 
Author: Yao Zhong (https://sketchfab.com/yaoz2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bedroom-empty-wip-56d51ffc593e4c74bc0e4f910bf23568
Title: Bedroom (Empty)  ----> WIP
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    wall_b_0: THREE.Mesh
    wall_l_0: THREE.Mesh
    wooden_floor_0: THREE.Mesh
    wooden_cover_l_3_0: THREE.Mesh
    wooden_cover_l_2_0: THREE.Mesh
    wooden_cover_l_1_0: THREE.Mesh
    wall_r_0: THREE.Mesh
    wooden_cover_l_curve1_0: THREE.Mesh
    wooden_cover_l_curve2_0: THREE.Mesh
    wooden_cover_l_5_0: THREE.Mesh
    wooden_cover_l_4_0: THREE.Mesh
    wooden_cover_r_3_0: THREE.Mesh
    wooden_cover_b_3_0: THREE.Mesh
    wooden_cover_f_0: THREE.Mesh
    wooden_cover_r_curve1_0: THREE.Mesh
    wooden_cover_r_2_0: THREE.Mesh
    wooden_cover_r_1_0: THREE.Mesh
    wooden_cover_b_1_0: THREE.Mesh
    wooden_cover_b_2_0: THREE.Mesh
    wooden_cover_b_curve_0: THREE.Mesh
    windows_frame_0: THREE.Mesh
    windows_0: THREE.Mesh
    screw_window_L1_0: THREE.Mesh
    screw_window_L2_0: THREE.Mesh
    certain_hanger_0: THREE.Mesh
    Plane_0: THREE.Mesh
    windows001_0: THREE.Mesh
  }
  materials: {
    Wall_B: THREE.MeshStandardMaterial
    Wall_R: THREE.MeshStandardMaterial
    Floor: THREE.MeshStandardMaterial
    wood01: THREE.MeshStandardMaterial
    Wall_L: THREE.MeshStandardMaterial
    windows_frame: THREE.MeshStandardMaterial
    Root: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function BackgroundModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/bg.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={10}>
        <mesh geometry={nodes.wall_b_0.geometry} material={materials.Wall_B} scale={[1, 0.819, 1]} />
        <mesh geometry={nodes.wall_l_0.geometry} material={materials.Wall_R} position={[0, 0.362, 0]} />
        <mesh geometry={nodes.wooden_floor_0.geometry} material={materials.Floor} />
        <mesh geometry={nodes.wooden_cover_l_3_0.geometry} material={materials.wood01} position={[0, -0.333, 0]} />
        <mesh geometry={nodes.wooden_cover_l_2_0.geometry} material={materials.wood01} position={[0, -0.333, 0]} />
        <mesh geometry={nodes.wooden_cover_l_1_0.geometry} material={materials.wood01} position={[0, -0.333, 0]} />
        <mesh geometry={nodes.wall_r_0.geometry} material={materials.Wall_L} position={[0, -0.333, 0]} />
        <mesh geometry={nodes.wooden_cover_l_curve1_0.geometry} material={materials.wood01} position={[0, -0.333, 0]} />
        <mesh geometry={nodes.wooden_cover_l_curve2_0.geometry} material={materials.wood01} position={[0, -0.333, 0]} />
        <mesh geometry={nodes.wooden_cover_l_5_0.geometry} material={materials.wood01} position={[0, -0.333, 0]} />
        <mesh geometry={nodes.wooden_cover_l_4_0.geometry} material={materials.wood01} position={[0, -0.333, 0]} />
        <mesh geometry={nodes.wooden_cover_r_3_0.geometry} material={materials.wood01} position={[0, 0.362, 0]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.wooden_cover_b_3_0.geometry} material={materials.wood01} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.wooden_cover_f_0.geometry} material={materials.wood01} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.wooden_cover_r_curve1_0.geometry} material={materials.wood01} position={[0, 0.301, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.wooden_cover_r_2_0.geometry} material={materials.wood01} position={[0, 0.301, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.wooden_cover_r_1_0.geometry} material={materials.wood01} position={[0, 0.301, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.wooden_cover_b_1_0.geometry} material={materials.wood01} position={[0, 0.296, 0]} rotation={[0, 0, 3.141]} />
        <mesh geometry={nodes.wooden_cover_b_2_0.geometry} material={materials.wood01} position={[0, 0.296, 0]} rotation={[0, 0, 3.141]} />
        <mesh geometry={nodes.wooden_cover_b_curve_0.geometry} material={materials.wood01} position={[0, 0.296, 0]} rotation={[0, 0, 3.141]} />
        <mesh geometry={nodes.windows_frame_0.geometry} material={materials.windows_frame} position={[0, -0.372, 0]} />
        <mesh geometry={nodes.windows_0.geometry} material={materials.windows_frame} position={[-2.212, 1.41, 1.098]} rotation={[0, 0, -Math.PI / 4]} />
        <mesh geometry={nodes.screw_window_L1_0.geometry} material={materials.Root} position={[-2.203, 1.419, 1.298]} />
        <mesh geometry={nodes.screw_window_L2_0.geometry} material={materials.Root} position={[-2.203, 1.419, 0.93]} />
        <mesh geometry={nodes.certain_hanger_0.geometry} material={materials.Root} position={[-2.155, 0.916, 1.544]} scale={[0.797, 1, 1]} />
        <mesh geometry={nodes.Plane_0.geometry} material={materials.Root} position={[-2.121, 0.898, 1.103]} />
        <mesh geometry={nodes.windows001_0.geometry} material={materials.windows_frame} position={[-2.212, 0.393, 1.098]} rotation={[0, 0, Math.PI / 4]} />
      </group>
    </group>
  )
}

useGLTF.preload('/bg.glb')
