/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/wardrobe-3.glb --t 
Author: rizky alamsyah (https://sketchfab.com/rizki29)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wardrobe-e48bb01993c7464ea09a02465c87d25d
Title: Wardrobe
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    door_L__0: THREE.Mesh
    door_R__0: THREE.Mesh
    wardrobe__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Wardrobe3(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/wardrobe-3.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.wardrobe__0.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.door_L__0.geometry} material={materials['Scene_-_Root']} position={[-0.669, -0.373, 1.043]} />
        <mesh geometry={nodes.door_R__0.geometry} material={materials['Scene_-_Root']} position={[0.669, -0.373, 1.043]} />
      </group>
    </group>
  )
}

useGLTF.preload('/wardrobe-3.glb')
