/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/wardrobe-8.glb --t 
Author: DKDTheGreat1 (https://sketchfab.com/DKDTheGreat1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wardrobe-low-poly-adae92e3e6ed4302adaf37f96ca925ba
Title: Wardrobe (Low poly)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
  }
  materials: {
    Main: THREE.MeshStandardMaterial
    silver: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Wardrobe8(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/wardrobe-8.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Main} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Main} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.silver} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.silver} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.silver} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.silver} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.silver} />
    </group>
  )
}

useGLTF.preload('/wardrobe-8.glb')
