/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/wardrobe-6.glb --t 
Author: ixMkc1 (https://sketchfab.com/ixMkc1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wardrobe-low-poly-84e8fe47ea02466aa7276a79ee27e6e0
Title: Wardrobe - Low poly
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    antique_Material1_0: THREE.Mesh
  }
  materials: {
    ['Material.1']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Wardrobe6(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/wardrobe-6.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.antique_Material1_0.geometry} material={materials['Material.1']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/wardrobe-6.glb')
