/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/wardrobe-2.glb --t 
Author: Livia Chandra (https://sketchfab.com/VeritasCH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wardrobe-0ffc613382464390892f278e75074c9c
Title: Wardrobe
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_0: THREE.Mesh
    Cube001_0: THREE.Mesh
    Cube002_0: THREE.Mesh
    Cube003_0: THREE.Mesh
    Cube004_0: THREE.Mesh
    Cube005_0: THREE.Mesh
    Cube006_0: THREE.Mesh
    Cube007_0: THREE.Mesh
    Cube008_0: THREE.Mesh
    Cube009_0: THREE.Mesh
    Cube010_0: THREE.Mesh
    Cylinder_0: THREE.Mesh
    Cylinder001_0: THREE.Mesh
    Cylinder002_0: THREE.Mesh
    Cylinder003_0: THREE.Mesh
    Cylinder004_0: THREE.Mesh
    Cylinder005_0: THREE.Mesh
    Cylinder006_0: THREE.Mesh
    Cylinder007_0: THREE.Mesh
    Cube011_0: THREE.Mesh
    Cube012_0: THREE.Mesh
    Cube013_0: THREE.Mesh
    Cube014_0: THREE.Mesh
  }
  materials: {
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    Spot: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Wardrobe2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/wardrobe-2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.007']} position={[0, 0, 2.1]} />
        <mesh geometry={nodes.Cube001_0.geometry} material={materials['Material.011']} position={[0.969, 0, 0]} />
        <mesh geometry={nodes.Cube002_0.geometry} material={materials['Material.003']} position={[0.964, -1.312, 2.064]} />
        <mesh geometry={nodes.Cube003_0.geometry} material={materials['Material.002']} position={[0.969, 1.302, 2.051]} />
        <mesh geometry={nodes.Cube004_0.geometry} material={materials['Material.001']} position={[0.969, 0, 4.119]} />
        <mesh geometry={nodes.Cube005_0.geometry} material={materials['Material.006']} position={[0.969, 0, 1.026]} />
        <mesh geometry={nodes.Cube006_0.geometry} material={materials['Material.010']} position={[0.969, 0.011, 0.525]} />
        <mesh geometry={nodes.Cube007_0.geometry} material={materials['Material.008']} position={[1.949, -0.657, 0.513]} />
        <mesh geometry={nodes.Cube008_0.geometry} material={materials['Material.009']} position={[1.949, 0.666, 0.513]} />
        <mesh geometry={nodes.Cube009_0.geometry} material={materials['Material.004']} position={[1.82, -0.643, 2.581]} />
        <mesh geometry={nodes.Cube010_0.geometry} material={materials['Material.005']} position={[1.82, 0.649, 2.579]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1.01, 1]} />
        <mesh geometry={nodes.Cylinder_0.geometry} material={materials['Material.016']} position={[1.96, -0.108, 2.386]} rotation={[Math.PI / 2, 1.571, 0]} />
        <mesh geometry={nodes.Cylinder001_0.geometry} material={materials['Material.015']} position={[1.96, -0.108, 2.799]} rotation={[Math.PI / 2, 1.571, 0]} />
        <mesh geometry={nodes.Cylinder002_0.geometry} material={materials['Material.012']} position={[1.96, 0.139, 2.799]} rotation={[Math.PI / 2, 1.571, 0]} />
        <mesh geometry={nodes.Cylinder003_0.geometry} material={materials['Material.013']} position={[1.96, 0.139, 2.386]} rotation={[Math.PI / 2, 1.571, 0]} />
        <mesh geometry={nodes.Cylinder004_0.geometry} material={materials['Material.022']} position={[1.96, 0.139, 0.583]} rotation={[Math.PI / 2, 1.571, 0]} />
        <mesh geometry={nodes.Cylinder005_0.geometry} material={materials['Material.023']} position={[1.96, 0.139, 0.443]} rotation={[Math.PI / 2, 1.571, 0]} />
        <mesh geometry={nodes.Cylinder006_0.geometry} material={materials.Spot} position={[1.96, -0.118, 0.443]} rotation={[Math.PI / 2, 1.571, 0]} />
        <mesh geometry={nodes.Cylinder007_0.geometry} material={materials['Material.018']} position={[1.96, -0.118, 0.583]} rotation={[Math.PI / 2, 1.571, 0]} />
        <mesh geometry={nodes.Cube011_0.geometry} material={materials['Material.014']} position={[2.008, 0.13, 2.606]} />
        <mesh geometry={nodes.Cube012_0.geometry} material={materials['Material.017']} position={[2.008, -0.101, 2.606]} />
        <mesh geometry={nodes.Cube013_0.geometry} material={materials['Material.020']} position={[1.993, -0.12, 0.523]} />
        <mesh geometry={nodes.Cube014_0.geometry} material={materials['Material.021']} position={[1.993, 0.136, 0.523]} />
      </group>
    </group>
  )
}

useGLTF.preload('/wardrobe-2.glb')
