/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/wardrobe-7.glb --t 
Author: saintkastiell (https://sketchfab.com/saintkastiell)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wardrobe-25122-ede879655ff444a2831dde070370b20c
Title: Wardrobe 25122
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Box002_NCS_S2002-Y50R_semiglos_0']: THREE.Mesh
    ['Box003_NCS_S2002-Y50R_semiglos_0']: THREE.Mesh
    ['VIFS072_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS077_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS074_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS076_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS073_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS075_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS078_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS083_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS080_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS081_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS082_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS079_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS038_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS035_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS039_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS040_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS036_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS037_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS041_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS043_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS044_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS046_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS042_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS045_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS022_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS023_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS024_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS025_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS031_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS028_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS026_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS021_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS020_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS029_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS030_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS095_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS068_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS065_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS057_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS060_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS061_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS062_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS066_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS063_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS096_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS059_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS058_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS067_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS033_U702_ST9_��������������_����������_0']: THREE.Mesh
    VIFS047_Glass_0: THREE.Mesh
    ['VIFS017_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS016_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS015_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS014_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS008_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS005_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS048_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS049_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS050_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS051_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS052_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS053_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS069_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS054_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS070_U702_ST9_��������������_����������_0']: THREE.Mesh
    VIFS084_Glass_0: THREE.Mesh
    ['VIFS085_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS086_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS087_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS055_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS001_NCS_S_5005-Y50R_semiglos_0']: THREE.Mesh
    ['VIFS002_NCS_S_5005-Y50R_semiglos_0']: THREE.Mesh
    ['VIFS032_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS009_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS013_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS019_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS034_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS056_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS071_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS018_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS012_NCS_S_5005-Y50R_semiglos_0']: THREE.Mesh
    ['VIFS011_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS010_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS007_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS006_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS090_NCS_S_5005-Y50R_semiglos_0']: THREE.Mesh
    ['Box004_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['Box005_U702_ST9_��������������_����������_0']: THREE.Mesh
    Box006_Light_0: THREE.Mesh
    Box007_Light_0: THREE.Mesh
    Box008_Light_0: THREE.Mesh
    Box009_Light_0: THREE.Mesh
    ['Box014_NCS_S2002-Y50R_semiglos_0']: THREE.Mesh
    ['Box011_NCS_S2002-Y50R_semiglos_0']: THREE.Mesh
    ['VIFS111_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS113_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS110_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS112_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS115_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS114_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS132_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS131_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS133_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS134_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS136_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS135_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS129_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS128_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS125_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS130_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS127_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS126_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS120_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS119_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS116_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS121_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS118_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS117_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['Box013_NCS_S2002-Y50R_semiglos_0']: THREE.Mesh
    ['VIFS104_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS109_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS156_NCS_S_5005-Y50R_semiglos_0']: THREE.Mesh
    ['VIFS155_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS151_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS149_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS148_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS122_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS123_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS137_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS139_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS140_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS141_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS124_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS142_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS147_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS150_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS152_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS101_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS153_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS108_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS105_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS103_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS102_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS169_NCS_S_5005-Y50R_semiglos_0']: THREE.Mesh
    ['VIFS145_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS146_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS138_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS107_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS106_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS100_U702_ST9_��������������_����������_0']: THREE.Mesh
    ['VIFS099_U702_ST9_��������������_����������_0']: THREE.Mesh
    Rectangle004_Chrome_0: THREE.Mesh
    ['VIFS168_U702_ST9_��������������_����������_0']: THREE.Mesh
    VIFS167_Chrome_0: THREE.Mesh
    ['VIFS166_U702_ST9_��������������_����������_0']: THREE.Mesh
    VIFS165_Chrome_0: THREE.Mesh
    ['VIFS164_U702_ST9_��������������_����������_0']: THREE.Mesh
    VIFS163_Chrome_0: THREE.Mesh
    ['VIFS162_U702_ST9_��������������_����������_0']: THREE.Mesh
    VIFS161_Chrome_0: THREE.Mesh
    Rectangle001_Chrome_0: THREE.Mesh
    Line001_Light_0: THREE.Mesh
    Line002_Light_0: THREE.Mesh
    Rectangle002_Chrome_0: THREE.Mesh
    Line003_Light_0: THREE.Mesh
    Rectangle003_Chrome_0: THREE.Mesh
    Line004_Light_0: THREE.Mesh
    ['VIFS098_NCS_S_5005-Y50R_semiglos_0']: THREE.Mesh
    ['VIFS097_NCS_S_5005-Y50R_semiglos_0']: THREE.Mesh
  }
  materials: {
    ['NCS_S2002-Y50R_semiglos']: THREE.MeshStandardMaterial
    U702_ST9: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    ['NCS_S_5005-Y50R_semiglos']: THREE.MeshStandardMaterial
    Light: THREE.MeshStandardMaterial
    Chrome: THREE.MeshStandardMaterial
  }
}

type ActionName = 'motion'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Wardrobe7(props: JSX.IntrinsicElements['group']) {
  const group = useRef<any>()
  const { nodes, materials, animations } = useGLTF('/wardrobe-7.glb') as GLTFResult
  // const { actions } = useAnimations<any>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="4469575b14e343c79aeb8ea7ddbfaa3dfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Group009" position={[1530, 1299, 1099]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                  <group name="Box002" position={[-468.725, -190.5, 20]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_120" position={[232.225, 0, -9.5]}>
                      <mesh name="Box002_NCS_S2002-Y50R_semiglos_0" geometry={nodes['Box002_NCS_S2002-Y50R_semiglos_0'].geometry} material={materials['NCS_S2002-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="Box003" position={[470.175, -190.5, 20]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_123" position={[-225.675, 0, -9.5]}>
                      <mesh name="Box003_NCS_S2002-Y50R_semiglos_0" geometry={nodes['Box003_NCS_S2002-Y50R_semiglos_0'].geometry} material={materials['NCS_S2002-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="Group003" position={[211.5, 23, -887]}>
                    <group name="VIFS072" position={[190.5, 8, -9]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_127" position={[169, -1075, -8]}>
                        <mesh name="VIFS072_U702_ST9_��������������_����������_0" geometry={nodes['VIFS072_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS077" position={[0, 8, -66]}>
                      <group name="Object_130" position={[288.5, -231, -8]}>
                        <mesh name="VIFS077_U702_ST9_��������������_����������_0" geometry={nodes['VIFS077_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS074" position={[0, 125, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_133" position={[288.5, -1089, -8]}>
                        <mesh name="VIFS074_U702_ST9_��������������_����������_0" geometry={nodes['VIFS074_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS076" position={[0, -125, 0]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_139" position={[288.5, -1084, -8]}>
                        <mesh name="VIFS076_U702_ST9_��������������_����������_0" geometry={nodes['VIFS076_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS073" position={[-190.5, 8, -9]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_142" position={[169, -1075, -8]}>
                        <mesh name="VIFS073_U702_ST9_��������������_����������_0" geometry={nodes['VIFS073_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS075" position={[0, -109, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_136" position={[288.5, -1089, -8]}>
                        <mesh name="VIFS075_U702_ST9_��������������_����������_0" geometry={nodes['VIFS075_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                  </group>
                  <group name="Group004" position={[211.5, 23, -1087]}>
                    <group name="VIFS078" position={[190.5, 8, -9]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_146" position={[169, -1075, -8]}>
                        <mesh name="VIFS078_U702_ST9_��������������_����������_0" geometry={nodes['VIFS078_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS083" position={[0, 8, -66]}>
                      <group name="Object_149" position={[288.5, -231, -8]}>
                        <mesh name="VIFS083_U702_ST9_��������������_����������_0" geometry={nodes['VIFS083_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS080" position={[0, 125, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_152" position={[288.5, -1089, -8]}>
                        <mesh name="VIFS080_U702_ST9_��������������_����������_0" geometry={nodes['VIFS080_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS081" position={[0, -109, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_155" position={[288.5, -1089, -8]}>
                        <mesh name="VIFS081_U702_ST9_��������������_����������_0" geometry={nodes['VIFS081_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS082" position={[0, -125, 0]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_158" position={[288.5, -1084, -8]}>
                        <mesh name="VIFS082_U702_ST9_��������������_����������_0" geometry={nodes['VIFS082_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS079" position={[-190.5, 8, -9]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_161" position={[169, -1075, -8]}>
                        <mesh name="VIFS079_U702_ST9_��������������_����������_0" geometry={nodes['VIFS079_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                  </group>
                  <group name="Group005" position={[-211.5, 23, -887]}>
                    <group name="VIFS038" position={[0, -109, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_168" position={[-288.5, -1089, -8]}>
                        <mesh name="VIFS038_U702_ST9_��������������_����������_0" geometry={nodes['VIFS038_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS035" position={[-190.5, 8, -9]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_171" position={[-169, -1075, -8]}>
                        <mesh name="VIFS035_U702_ST9_��������������_����������_0" geometry={nodes['VIFS035_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS039" position={[0, -125, 0]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_174" position={[-288.5, -1084, -8]}>
                        <mesh name="VIFS039_U702_ST9_��������������_����������_0" geometry={nodes['VIFS039_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS040" position={[0, 8, -66]}>
                      <group name="Object_177" position={[-288.5, -231, -8]}>
                        <mesh name="VIFS040_U702_ST9_��������������_����������_0" geometry={nodes['VIFS040_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS036" position={[190.5, 8, -9]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_180" position={[-169, -1075, -8]}>
                        <mesh name="VIFS036_U702_ST9_��������������_����������_0" geometry={nodes['VIFS036_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS037" position={[0, 125, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_165" position={[-288.5, -1089, -8]}>
                        <mesh name="VIFS037_U702_ST9_��������������_����������_0" geometry={nodes['VIFS037_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                  </group>
                  <group name="Group006" position={[-211.5, 23, -1087]}>
                    <group name="VIFS041" position={[-190.5, 8, -9]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_184" position={[-169, -1075, -8]}>
                        <mesh name="VIFS041_U702_ST9_��������������_����������_0" geometry={nodes['VIFS041_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS043" position={[0, 125, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_187" position={[-288.5, -1089, -8]}>
                        <mesh name="VIFS043_U702_ST9_��������������_����������_0" geometry={nodes['VIFS043_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS044" position={[0, -109, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_190" position={[-288.5, -1089, -8]}>
                        <mesh name="VIFS044_U702_ST9_��������������_����������_0" geometry={nodes['VIFS044_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS046" position={[0, 8, -66]}>
                      <group name="Object_193" position={[-288.5, -231, -8]}>
                        <mesh name="VIFS046_U702_ST9_��������������_����������_0" geometry={nodes['VIFS046_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS042" position={[190.5, 8, -9]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_196" position={[-169, -1075, -8]}>
                        <mesh name="VIFS042_U702_ST9_��������������_����������_0" geometry={nodes['VIFS042_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS045" position={[0, -125, 0]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_199" position={[-288.5, -1084, -8]}>
                        <mesh name="VIFS045_U702_ST9_��������������_����������_0" geometry={nodes['VIFS045_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                  </group>
                  <group name="Group007" position={[-211.5, 23, -161.5]}>
                    <group name="VIFS022" position={[92.5, 8, 16]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_203" position={[-169, -1153.5, -4]}>
                        <mesh name="VIFS022_U702_ST9_��������������_����������_0" geometry={nodes['VIFS022_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS023" position={[-47, 8, 16]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_206" position={[-241.5, -1153.5, -4]}>
                        <mesh name="VIFS023_U702_ST9_��������������_����������_0" geometry={nodes['VIFS023_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS024" position={[-140, 8, 16]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_209" position={[-148.5, -1153.5, -4]}>
                        <mesh name="VIFS024_U702_ST9_��������������_����������_0" geometry={nodes['VIFS024_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS025" position={[139.5, 8, 16]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_212" position={[-428, -1153.5, -4]}>
                        <mesh name="VIFS025_U702_ST9_��������������_����������_0" geometry={nodes['VIFS025_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS031" position={[-190.5, 8, 2]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_215" position={[-169, -1139.5, -8]}>
                        <mesh name="VIFS031_U702_ST9_��������������_����������_0" geometry={nodes['VIFS031_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS028" position={[0, -109, 16]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_218" position={[-288.5, -1153.5, -8]}>
                        <mesh name="VIFS028_U702_ST9_��������������_����������_0" geometry={nodes['VIFS028_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS026" position={[0, 8, -28.5]}>
                      <group name="Object_221" position={[-288.5, -231, -8]}>
                        <mesh name="VIFS026_U702_ST9_��������������_����������_0" geometry={nodes['VIFS026_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS021" position={[-0.5, 8, 16]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_224" position={[-169, -1153.5, -4]}>
                        <mesh name="VIFS021_U702_ST9_��������������_����������_0" geometry={nodes['VIFS021_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS020" position={[-93.5, 8, 16]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_227" position={[-169, -1153.5, -4]}>
                        <mesh name="VIFS020_U702_ST9_��������������_����������_0" geometry={nodes['VIFS020_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS029" position={[0, 125, 16]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_230" position={[-288.5, -1153.5, -8]}>
                        <mesh name="VIFS029_U702_ST9_��������������_����������_0" geometry={nodes['VIFS029_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS030" position={[190.5, 8, 2]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_236" position={[-169, -1139.5, -8]}>
                        <mesh name="VIFS030_U702_ST9_��������������_����������_0" geometry={nodes['VIFS030_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS095" position={[0, -125, -37.5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_233" position={[-288.5, -1084, -8]}>
                        <mesh name="VIFS095_U702_ST9_��������������_����������_0" geometry={nodes['VIFS095_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                  </group>
                  <group name="Group008" position={[211.5, 23, -161.5]}>
                    <group name="VIFS068" position={[190.5, 8, 2]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_240" position={[169, -1139.5, -8]}>
                        <mesh name="VIFS068_U702_ST9_��������������_����������_0" geometry={nodes['VIFS068_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS065" position={[0, -109, 16]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_243" position={[288.5, -1153.5, -8]}>
                        <mesh name="VIFS065_U702_ST9_��������������_����������_0" geometry={nodes['VIFS065_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS057" position={[93.5, 8, 16]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_252" position={[169, -1153.5, -4]}>
                        <mesh name="VIFS057_U702_ST9_��������������_����������_0" geometry={nodes['VIFS057_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS060" position={[47, 8, 16]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_255" position={[241.5, -1153.5, -4]}>
                        <mesh name="VIFS060_U702_ST9_��������������_����������_0" geometry={nodes['VIFS060_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS061" position={[140, 8, 16]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_258" position={[148.5, -1153.5, -4]}>
                        <mesh name="VIFS061_U702_ST9_��������������_����������_0" geometry={nodes['VIFS061_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS062" position={[-139.5, 8, 16]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_261" position={[428, -1153.5, -4]}>
                        <mesh name="VIFS062_U702_ST9_��������������_����������_0" geometry={nodes['VIFS062_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS066" position={[0, 125, 16]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_264" position={[288.5, -1153.5, -8]}>
                        <mesh name="VIFS066_U702_ST9_��������������_����������_0" geometry={nodes['VIFS066_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS063" position={[0, 8, -28.5]}>
                      <group name="Object_267" position={[288.5, -231, -8]}>
                        <mesh name="VIFS063_U702_ST9_��������������_����������_0" geometry={nodes['VIFS063_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS096" position={[0, -125, -37.5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_270" position={[-288.5, -1084, -8]}>
                        <mesh name="VIFS096_U702_ST9_��������������_����������_0" geometry={nodes['VIFS096_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS059" position={[-92.5, 8, 16]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_246" position={[169, -1153.5, -4]}>
                        <mesh name="VIFS059_U702_ST9_��������������_����������_0" geometry={nodes['VIFS059_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS058" position={[0.5, 8, 16]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_249" position={[169, -1153.5, -4]}>
                        <mesh name="VIFS058_U702_ST9_��������������_����������_0" geometry={nodes['VIFS058_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS067" position={[-190.5, 8, 2]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_273" position={[169, -1139.5, -8]}>
                        <mesh name="VIFS067_U702_ST9_��������������_����������_0" geometry={nodes['VIFS067_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                  </group>
                  <group name="VIFS033" position={[-236.5, 40, -1195]}>
                    <group name="Object_6" position={[-263.5, -440, -8]}>
                      <mesh name="VIFS033_U702_ST9_��������������_����������_0" geometry={nodes['VIFS033_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS047" position={[-236.5, 40, -96]}>
                    <group name="Object_9" position={[-263.5, -240, -3]}>
                      <mesh name="VIFS047_Glass_0" geometry={nodes.VIFS047_Glass_0.geometry} material={materials.Glass} />
                    </group>
                  </group>
                  <group name="VIFS017" position={[-236.5, 40, -232]}>
                    <group name="Object_12" position={[-263.5, -440, -8]}>
                      <mesh name="VIFS017_U702_ST9_��������������_����������_0" geometry={nodes['VIFS017_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS016" position={[-440, 40, -107]}>
                    <group name="Object_15" position={[-60, -440, -8]}>
                      <mesh name="VIFS016_U702_ST9_��������������_����������_0" geometry={nodes['VIFS016_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS015" position={[-236.5, 40, -505]}>
                    <group name="Object_18" position={[-263.5, -440, -8]}>
                      <mesh name="VIFS015_U702_ST9_��������������_����������_0" geometry={nodes['VIFS015_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS014" position={[-236.5, 40, -779]}>
                    <group name="Object_21" position={[-263.5, -440, -8]}>
                      <mesh name="VIFS014_U702_ST9_��������������_����������_0" geometry={nodes['VIFS014_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS008" position={[0, 10, -1211]}>
                    <group name="Object_24" position={[-500, -410, -8]}>
                      <mesh name="VIFS008_U702_ST9_��������������_����������_0" geometry={nodes['VIFS008_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS005" position={[0, 5, 1251]}>
                    <group name="Object_27" position={[-500, -405, -8]}>
                      <mesh name="VIFS005_U702_ST9_��������������_����������_0" geometry={nodes['VIFS005_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS048" position={[-236.5, 5, 885]}>
                    <group name="Object_30" position={[-263.5, -405, -8]}>
                      <mesh name="VIFS048_U702_ST9_��������������_����������_0" geometry={nodes['VIFS048_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS049" position={[-236.5, 10, 210]}>
                    <group name="Object_33" position={[-263.5, -410, -8]}>
                      <mesh name="VIFS049_U702_ST9_��������������_����������_0" geometry={nodes['VIFS049_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS050" position={[-236.5, 10, 523]}>
                    <group name="Object_36" position={[-263.5, -410, -8]}>
                      <mesh name="VIFS050_U702_ST9_��������������_����������_0" geometry={nodes['VIFS050_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS051" position={[236.5, 40, -779]}>
                    <group name="Object_39" position={[263.5, -440, -8]}>
                      <mesh name="VIFS051_U702_ST9_��������������_����������_0" geometry={nodes['VIFS051_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS052" position={[236.5, 40, -505]}>
                    <group name="Object_42" position={[263.5, -440, -8]}>
                      <mesh name="VIFS052_U702_ST9_��������������_����������_0" geometry={nodes['VIFS052_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS053" position={[440, 40, -107]}>
                    <group name="Object_45" position={[60, -440, -8]}>
                      <mesh name="VIFS053_U702_ST9_��������������_����������_0" geometry={nodes['VIFS053_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS069" position={[440, -102, -987]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_48" position={[60, -968, -8]}>
                      <mesh name="VIFS069_U702_ST9_��������������_����������_0" geometry={nodes['VIFS069_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS054" position={[236.5, 40, -232]}>
                    <group name="Object_51" position={[263.5, -440, -8]}>
                      <mesh name="VIFS054_U702_ST9_��������������_����������_0" geometry={nodes['VIFS054_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS070" position={[236.5, 40, -1195]}>
                    <group name="Object_54" position={[263.5, -440, -8]}>
                      <mesh name="VIFS070_U702_ST9_��������������_����������_0" geometry={nodes['VIFS070_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS084" position={[236.5, 40, -96]}>
                    <group name="Object_57" position={[263.5, -240, -3]}>
                      <mesh name="VIFS084_Glass_0" geometry={nodes.VIFS084_Glass_0.geometry} material={materials.Glass} />
                    </group>
                  </group>
                  <group name="VIFS085" position={[236.5, 5, 885]}>
                    <group name="Object_60" position={[263.5, -405, -8]}>
                      <mesh name="VIFS085_U702_ST9_��������������_����������_0" geometry={nodes['VIFS085_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS086" position={[236.5, 10, 210]}>
                    <group name="Object_63" position={[263.5, -410, -8]}>
                      <mesh name="VIFS086_U702_ST9_��������������_����������_0" geometry={nodes['VIFS086_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS087" position={[236.5, 10, 523]}>
                    <group name="Object_66" position={[263.5, -410, -8]}>
                      <mesh name="VIFS087_U702_ST9_��������������_����������_0" geometry={nodes['VIFS087_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS055" position={[440, -102, -169.5]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_69" position={[60, -1113.5, -8]}>
                      <mesh name="VIFS055_U702_ST9_��������������_����������_0" geometry={nodes['VIFS055_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS001" position={[-490.5, -170, 0]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_72" position={[-30, -1299, -9.5]}>
                      <mesh name="VIFS001_NCS_S_5005-Y50R_semiglos_0" geometry={nodes['VIFS001_NCS_S_5005-Y50R_semiglos_0'].geometry} material={materials['NCS_S_5005-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="VIFS002" position={[490.5, 0, 0]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_75" position={[-200, -1299, -9.5]}>
                      <mesh name="VIFS002_NCS_S_5005-Y50R_semiglos_0" geometry={nodes['VIFS002_NCS_S_5005-Y50R_semiglos_0'].geometry} material={materials['NCS_S_5005-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="VIFS032" position={[-440, -102, -987]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_78" position={[-60, -968, -8]}>
                      <mesh name="VIFS032_U702_ST9_��������������_����������_0" geometry={nodes['VIFS032_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS009" position={[0, 5, 20]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_81" position={[-195, -1319, -8]}>
                      <mesh name="VIFS009_U702_ST9_��������������_����������_0" geometry={nodes['VIFS009_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS013" position={[0, -10, -1259]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_84" position={[-210, -40, -8]}>
                      <mesh name="VIFS013_U702_ST9_��������������_����������_0" geometry={nodes['VIFS013_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS019" position={[-423, 48, -169.5]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_87" position={[-152, -1129.5, -8]}>
                      <mesh name="VIFS019_U702_ST9_��������������_����������_0" geometry={nodes['VIFS019_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS034" position={[-423, 48, -987]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_90" position={[-152, -984, -8]}>
                      <mesh name="VIFS034_U702_ST9_��������������_����������_0" geometry={nodes['VIFS034_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS056" position={[423, 48, -169.5]} rotation={[Math.PI / 2, 1.571, 0]}>
                    <group name="Object_93" position={[152, -1129.5, -8]}>
                      <mesh name="VIFS056_U702_ST9_��������������_����������_0" geometry={nodes['VIFS056_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS071" position={[423, 48, -987]} rotation={[Math.PI / 2, 1.571, 0]}>
                    <group name="Object_96" position={[152, -984, -8]}>
                      <mesh name="VIFS071_U702_ST9_��������������_����������_0" geometry={nodes['VIFS071_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS018" position={[-440, -102, -169.5]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_99" position={[-60, -1113.5, -8]}>
                      <mesh name="VIFS018_U702_ST9_��������������_����������_0" geometry={nodes['VIFS018_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS012" position={[0, -190.5, 1279]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_102" position={[-500, -2578, -9.5]}>
                      <mesh name="VIFS012_NCS_S_5005-Y50R_semiglos_0" geometry={nodes['VIFS012_NCS_S_5005-Y50R_semiglos_0'].geometry} material={materials['NCS_S_5005-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="VIFS011" position={[236.5, 196, 24]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_105" position={[993.5, -1323, -4]}>
                      <mesh name="VIFS011_U702_ST9_��������������_����������_0" geometry={nodes['VIFS011_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS010" position={[-236.5, 196, 24]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_108" position={[-263.5, -1323, -4]}>
                      <mesh name="VIFS010_U702_ST9_��������������_����������_0" geometry={nodes['VIFS010_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS007" position={[0, -172, -1259]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_111" position={[-500, -40, -8]}>
                      <mesh name="VIFS007_U702_ST9_��������������_����������_0" geometry={nodes['VIFS007_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS006" position={[0, 152, -1259]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_114" position={[-500, -40, -8]}>
                      <mesh name="VIFS006_U702_ST9_��������������_����������_0" geometry={nodes['VIFS006_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS090" position={[0, -189.5, -1260]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_117" position={[-510, -121, -9.5]}>
                      <mesh name="VIFS090_NCS_S_5005-Y50R_semiglos_0" geometry={nodes['VIFS090_NCS_S_5005-Y50R_semiglos_0'].geometry} material={materials['NCS_S_5005-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="Box004" position={[-473, 10, -1299]}>
                    <mesh name="Box004_U702_ST9_��������������_����������_0" geometry={nodes['Box004_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                  </group>
                  <group name="Box005" position={[473, 10, -1299]}>
                    <mesh name="Box005_U702_ST9_��������������_����������_0" geometry={nodes['Box005_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                  </group>
                  <group name="Box006" position={[-467.579, -72, -505.5]}>
                    <group name="Object_280" position={[0, 0, -793.5]}>
                      <mesh name="Box006_Light_0" geometry={nodes.Box006_Light_0.geometry} material={materials.Light} />
                    </group>
                  </group>
                  <group name="Box007" position={[-467.579, -72, 166.5]}>
                    <group name="Object_283" position={[0, 0, -793.5]}>
                      <mesh name="Box007_Light_0" geometry={nodes.Box007_Light_0.geometry} material={materials.Light} />
                    </group>
                  </group>
                  <group name="Box008" position={[467.756, -72, -505.5]}>
                    <group name="Object_286" position={[0, 0, -793.5]}>
                      <mesh name="Box008_Light_0" geometry={nodes.Box008_Light_0.geometry} material={materials.Light} />
                    </group>
                  </group>
                  <group name="Box009" position={[467.756, -72, 166.5]}>
                    <group name="Object_289" position={[0, 0, -793.5]}>
                      <mesh name="Box009_Light_0" geometry={nodes.Box009_Light_0.geometry} material={materials.Light} />
                    </group>
                  </group>
                  <group name="VRayLight001" position={[-464.443, -72, 572]} rotation={[Math.PI / 2, -1.571, 0]} />
                  <group name="VRayLight002" position={[464.613, -72, 572]} rotation={[Math.PI / 2, 1.571, 0]} />
                  <group name="VRayLight003" position={[-464.443, -72, -505.5]} rotation={[Math.PI / 2, -1.571, 0]} scale={[1, 0.398, 1]} />
                  <group name="VRayLight004" position={[464.613, -72, -505.5]} rotation={[Math.PI / 2, 1.571, 0]} scale={[1, 0.398, 1]} />
                </group>
                <group name="Group014" position={[865, 1299, 299.5]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Box014" position={[2.369, -290, 20]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_297" position={[-174.869, 0, -9.5]}>
                      <mesh name="Box014_NCS_S2002-Y50R_semiglos_0" geometry={nodes['Box014_NCS_S2002-Y50R_semiglos_0'].geometry} material={materials['NCS_S2002-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="Box011" position={[433.067, -290, 20]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_300" position={[-174.567, 0, -9.5]}>
                      <mesh name="Box011_NCS_S2002-Y50R_semiglos_0" geometry={nodes['Box011_NCS_S2002-Y50R_semiglos_0'].geometry} material={materials['NCS_S2002-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="Group010" position={[-602, 22.5, -887]}>
                    <group name="VIFS111" position={[0, -225, 0]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_321" position={[-263, -1084, -8]}>
                        <mesh name="VIFS111_U702_ST9_��������������_����������_0" geometry={nodes['VIFS111_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS113" position={[0, 225, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_306" position={[-263, -1089, -8]}>
                        <mesh name="VIFS113_U702_ST9_��������������_����������_0" geometry={nodes['VIFS113_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS110" position={[0, 8, -66]}>
                      <group name="Object_309" position={[-263, -131, -8]}>
                        <mesh name="VIFS110_U702_ST9_��������������_����������_0" geometry={nodes['VIFS110_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS112" position={[0, -209, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_312" position={[-263, -1089, -8]}>
                        <mesh name="VIFS112_U702_ST9_��������������_����������_0" geometry={nodes['VIFS112_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS115" position={[-165, 8, -9]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_315" position={[-269, -1075, -8]}>
                        <mesh name="VIFS115_U702_ST9_��������������_����������_0" geometry={nodes['VIFS115_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS114" position={[165, 8, -9]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_318" position={[-269, -1075, -8]}>
                        <mesh name="VIFS114_U702_ST9_��������������_����������_0" geometry={nodes['VIFS114_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                  </group>
                  <group name="Group011" position={[-230, 22.5, -887]}>
                    <group name="VIFS132" position={[0, -225, 0]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_340" position={[277, -1084, -8]}>
                        <mesh name="VIFS132_U702_ST9_��������������_����������_0" geometry={nodes['VIFS132_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS131" position={[0, 8, -66]}>
                      <group name="Object_325" position={[277, -131, -8]}>
                        <mesh name="VIFS131_U702_ST9_��������������_����������_0" geometry={nodes['VIFS131_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS133" position={[0, -209, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_328" position={[277, -1089, -8]}>
                        <mesh name="VIFS133_U702_ST9_��������������_����������_0" geometry={nodes['VIFS133_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS134" position={[0, 225, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_331" position={[277, -1089, -8]}>
                        <mesh name="VIFS134_U702_ST9_��������������_����������_0" geometry={nodes['VIFS134_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS136" position={[165, 8, -9]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_334" position={[269, -1075, -8]}>
                        <mesh name="VIFS136_U702_ST9_��������������_����������_0" geometry={nodes['VIFS136_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS135" position={[-165, 8, -9]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_337" position={[269, -1075, -8]}>
                        <mesh name="VIFS135_U702_ST9_��������������_����������_0" geometry={nodes['VIFS135_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                  </group>
                  <group name="Group012" position={[-230, 22.5, -1087]}>
                    <group name="VIFS129" position={[0, -225, 0]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_359" position={[277, -1084, -8]}>
                        <mesh name="VIFS129_U702_ST9_��������������_����������_0" geometry={nodes['VIFS129_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS128" position={[0, -209, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_344" position={[277, -1089, -8]}>
                        <mesh name="VIFS128_U702_ST9_��������������_����������_0" geometry={nodes['VIFS128_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS125" position={[165, 8, -9]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_347" position={[269, -1075, -8]}>
                        <mesh name="VIFS125_U702_ST9_��������������_����������_0" geometry={nodes['VIFS125_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS130" position={[0, 8, -66]}>
                      <group name="Object_350" position={[277, -131, -8]}>
                        <mesh name="VIFS130_U702_ST9_��������������_����������_0" geometry={nodes['VIFS130_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS127" position={[0, 225, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_353" position={[277, -1089, -8]}>
                        <mesh name="VIFS127_U702_ST9_��������������_����������_0" geometry={nodes['VIFS127_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS126" position={[-165, 8, -9]} rotation={[Math.PI / 2, 1.571, 0]}>
                      <group name="Object_356" position={[269, -1075, -8]}>
                        <mesh name="VIFS126_U702_ST9_��������������_����������_0" geometry={nodes['VIFS126_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                  </group>
                  <group name="Group013" position={[-602, 22.5, -1087]}>
                    <group name="VIFS120" position={[0, -225, 0]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_378" position={[-263, -1084, -8]}>
                        <mesh name="VIFS120_U702_ST9_��������������_����������_0" geometry={nodes['VIFS120_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS119" position={[0, -209, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_363" position={[-263, -1089, -8]}>
                        <mesh name="VIFS119_U702_ST9_��������������_����������_0" geometry={nodes['VIFS119_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS116" position={[-165, 8, -9]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_366" position={[-269, -1075, -8]}>
                        <mesh name="VIFS116_U702_ST9_��������������_����������_0" geometry={nodes['VIFS116_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS121" position={[0, 8, -66]}>
                      <group name="Object_369" position={[-263, -131, -8]}>
                        <mesh name="VIFS121_U702_ST9_��������������_����������_0" geometry={nodes['VIFS121_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS118" position={[0, 225, 5]} rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_372" position={[-263, -1089, -8]}>
                        <mesh name="VIFS118_U702_ST9_��������������_����������_0" geometry={nodes['VIFS118_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                    <group name="VIFS117" position={[165, 8, -9]} rotation={[Math.PI / 2, -1.571, 0]}>
                      <group name="Object_375" position={[-269, -1075, -8]}>
                        <mesh name="VIFS117_U702_ST9_��������������_����������_0" geometry={nodes['VIFS117_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                      </group>
                    </group>
                  </group>
                  <group name="Box013" position={[-833.441, -290, 20]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_527" position={[180.941, 0, -9.5]}>
                      <mesh name="Box013_NCS_S2002-Y50R_semiglos_0" geometry={nodes['Box013_NCS_S2002-Y50R_semiglos_0'].geometry} material={materials['NCS_S2002-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="VRayLight007" position={[436.5, 3.17, 441.818]} scale={[2.014, 1, 1]} />
                  <group name="VRayLight006" position={[-208, 3.17, 441.818]} />
                  <group name="VIFS104" position={[-416, 4.5, 1251]}>
                    <group name="Object_381" position={[-449, -305, -8]}>
                      <mesh name="VIFS104_U702_ST9_��������������_����������_0" geometry={nodes['VIFS104_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS109" position={[-627, 39.5, -779]}>
                    <group name="Object_384" position={[-238, -340, -8]}>
                      <mesh name="VIFS109_U702_ST9_��������������_����������_0" geometry={nodes['VIFS109_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS156" position={[475, -290, -20]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_387" position={[-30, -1279, -9.5]}>
                      <mesh name="VIFS156_NCS_S_5005-Y50R_semiglos_0" geometry={nodes['VIFS156_NCS_S_5005-Y50R_semiglos_0'].geometry} material={materials['NCS_S_5005-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="VIFS155" position={[685, -288.5, 20]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_390" position={[925.085, -1281.827, -8]}>
                      <mesh name="VIFS155_U702_ST9_��������������_����������_0" geometry={nodes['VIFS155_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS151" position={[439.5, 293.5, 24]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_393" position={[-430.5, -1323, -4]}>
                      <mesh name="VIFS151_U702_ST9_��������������_����������_0" geometry={nodes['VIFS151_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS149" position={[439.5, -272.5, -1259]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_396" position={[-430.5, -40, -8]}>
                      <mesh name="VIFS149_U702_ST9_��������������_����������_0" geometry={nodes['VIFS149_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS148" position={[439.5, 251.5, -1259]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_399" position={[-430.5, -40, -8]}>
                      <mesh name="VIFS148_U702_ST9_��������������_����������_0" geometry={nodes['VIFS148_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS122" position={[-627, 39.5, -1195]}>
                    <group name="Object_402" position={[-238, -340, -8]}>
                      <mesh name="VIFS122_U702_ST9_��������������_����������_0" geometry={nodes['VIFS122_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS123" position={[-205, 39.5, -1195]}>
                    <group name="Object_405" position={[252, -340, -8]}>
                      <mesh name="VIFS123_U702_ST9_��������������_����������_0" geometry={nodes['VIFS123_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS137" position={[-205, 39.5, -779]}>
                    <group name="Object_408" position={[252, -340, -8]}>
                      <mesh name="VIFS137_U702_ST9_��������������_����������_0" geometry={nodes['VIFS137_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS139" position={[-627, 4.5, 885]}>
                    <group name="Object_411" position={[-238, -305, -8]}>
                      <mesh name="VIFS139_U702_ST9_��������������_����������_0" geometry={nodes['VIFS139_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS140" position={[-627, 4.5, 523]}>
                    <group name="Object_414" position={[-238, -305, -8]}>
                      <mesh name="VIFS140_U702_ST9_��������������_����������_0" geometry={nodes['VIFS140_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS141" position={[-205, 4.5, 885]}>
                    <group name="Object_417" position={[252, -305, -8]}>
                      <mesh name="VIFS141_U702_ST9_��������������_����������_0" geometry={nodes['VIFS141_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS124" position={[-27, -202.5, -987]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_420" position={[60, -968, -8]}>
                      <mesh name="VIFS124_U702_ST9_��������������_����������_0" geometry={nodes['VIFS124_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS142" position={[-205, 4.5, 523]}>
                    <group name="Object_423" position={[252, -305, -8]}>
                      <mesh name="VIFS142_U702_ST9_��������������_����������_0" geometry={nodes['VIFS142_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS147" position={[439.5, 9.5, -1211]}>
                    <group name="Object_426" position={[-430.5, -310, -8]}>
                      <mesh name="VIFS147_U702_ST9_��������������_����������_0" geometry={nodes['VIFS147_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS150" position={[439.5, 4.5, 1251]}>
                    <group name="Object_429" position={[-430.5, -305, -8]}>
                      <mesh name="VIFS150_U702_ST9_��������������_����������_0" geometry={nodes['VIFS150_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS152" position={[439.5, 4.5, 885]}>
                    <group name="Object_432" position={[-430.5, -305, -8]}>
                      <mesh name="VIFS152_U702_ST9_��������������_����������_0" geometry={nodes['VIFS152_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS101" position={[-416, 9.5, -1211]}>
                    <group name="Object_435" position={[-449, -310, -8]}>
                      <mesh name="VIFS101_U702_ST9_��������������_����������_0" geometry={nodes['VIFS101_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS153" position={[439.5, 4.5, 523]}>
                    <group name="Object_438" position={[-430.5, -305, -8]}>
                      <mesh name="VIFS153_U702_ST9_��������������_����������_0" geometry={nodes['VIFS153_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS108" position={[-805, -202.5, -987]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_441" position={[-60, -968, -8]}>
                      <mesh name="VIFS108_U702_ST9_��������������_����������_0" geometry={nodes['VIFS108_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS105" position={[-416, 293.5, 24]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_444" position={[-449, -1323, -4]}>
                      <mesh name="VIFS105_U702_ST9_��������������_����������_0" geometry={nodes['VIFS105_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS103" position={[-416, -272.5, -1259]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_447" position={[-449, -40, -8]}>
                      <mesh name="VIFS103_U702_ST9_��������������_����������_0" geometry={nodes['VIFS103_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS102" position={[-416, 251.5, -1259]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_450" position={[-449, -40, -8]}>
                      <mesh name="VIFS102_U702_ST9_��������������_����������_0" geometry={nodes['VIFS102_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VRayLight005" position={[-630, 3.17, 441.818]} />
                  <group name="VIFS169" position={[-200.5, -290, -1260]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_454" position={[-666.5, -121, -9.5]}>
                      <mesh name="VIFS169_NCS_S_5005-Y50R_semiglos_0" geometry={nodes['VIFS169_NCS_S_5005-Y50R_semiglos_0'].geometry} material={materials['NCS_S_5005-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="VIFS145" position={[22, 9.5, -20]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_457" position={[-290, -1279, -8]}>
                      <mesh name="VIFS145_U702_ST9_��������������_����������_0" geometry={nodes['VIFS145_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS146" position={[857, 9.5, -20]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_460" position={[-290, -1279, -8]}>
                      <mesh name="VIFS146_U702_ST9_��������������_����������_0" geometry={nodes['VIFS146_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS138" position={[-44, 47.5, -987]} rotation={[Math.PI / 2, 1.571, 0]}>
                    <group name="Object_463" position={[252, -984, -8]}>
                      <mesh name="VIFS138_U702_ST9_��������������_����������_0" geometry={nodes['VIFS138_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS107" position={[-788, 47.5, -987]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_466" position={[-252, -984, -8]}>
                      <mesh name="VIFS107_U702_ST9_��������������_����������_0" geometry={nodes['VIFS107_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS106" position={[-416, 4.5, 20]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_469" position={[-295, -1319, -8]}>
                      <mesh name="VIFS106_U702_ST9_��������������_����������_0" geometry={nodes['VIFS106_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS100" position={[6, 9.5, -20]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_472" position={[-290, -1279, -8]}>
                      <mesh name="VIFS100_U702_ST9_��������������_����������_0" geometry={nodes['VIFS100_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS099" position={[-838, 9.5, -20]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_475" position={[-290, -1279, -8]}>
                      <mesh name="VIFS099_U702_ST9_��������������_����������_0" geometry={nodes['VIFS099_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="Rectangle004" position={[276.076, 3, -401.764]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_478" position={[1.276, -1.877, 342.059]}>
                      <mesh name="Rectangle004_Chrome_0" geometry={nodes.Rectangle004_Chrome_0.geometry} material={materials.Chrome} />
                    </group>
                  </group>
                  <group name="VIFS168" position={[-397.25, 3, 511.25]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_481" position={[-10.75, -3.75, 1.5]}>
                      <mesh name="VIFS168_U702_ST9_��������������_����������_0" geometry={nodes['VIFS168_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS167" position={[-205, 4.5, 476.757]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_484" position={[-203, -38.243, 0]}>
                      <mesh name="VIFS167_Chrome_0" geometry={nodes.VIFS167_Chrome_0.geometry} material={materials.Chrome} />
                    </group>
                  </group>
                  <group name="VIFS166" position={[-819.25, 3, 511.25]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_487" position={[-10.75, -3.75, 1.5]}>
                      <mesh name="VIFS166_U702_ST9_��������������_����������_0" geometry={nodes['VIFS166_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS165" position={[-627, 4.5, 476.757]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_490" position={[-203, -38.243, 0]}>
                      <mesh name="VIFS165_Chrome_0" geometry={nodes.VIFS165_Chrome_0.geometry} material={materials.Chrome} />
                    </group>
                  </group>
                  <group name="VIFS164" position={[40.75, 3, -347.75]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_493" position={[-10.75, -3.75, 1.5]}>
                      <mesh name="VIFS164_U702_ST9_��������������_����������_0" geometry={nodes['VIFS164_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS163" position={[439.5, 4.5, -382.243]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_496" position={[-409.5, -38.243, 0]}>
                      <mesh name="VIFS163_Chrome_0" geometry={nodes.VIFS163_Chrome_0.geometry} material={materials.Chrome} />
                    </group>
                  </group>
                  <group name="VIFS162" position={[40.75, 3, 511.25]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_499" position={[-10.75, -3.75, 1.5]}>
                      <mesh name="VIFS162_U702_ST9_��������������_����������_0" geometry={nodes['VIFS162_U702_ST9_��������������_����������_0'].geometry} material={materials.U702_ST9} />
                    </group>
                  </group>
                  <group name="VIFS161" position={[439.5, 4.5, 476.757]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_502" position={[-409.5, -38.243, 0]}>
                      <mesh name="VIFS161_Chrome_0" geometry={nodes.VIFS161_Chrome_0.geometry} material={materials.Chrome} />
                    </group>
                  </group>
                  <group name="Rectangle001" position={[-630, 3, 456.807]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_505" position={[1.276, -1.877, 342.059]}>
                      <mesh name="Rectangle001_Chrome_0" geometry={nodes.Rectangle001_Chrome_0.geometry} material={materials.Chrome} />
                    </group>
                  </group>
                  <group name="Line001" position={[-630, 3.17, 444.28]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_508" position={[0, 0.42, 342.059]}>
                      <mesh name="Line001_Light_0" geometry={nodes.Line001_Light_0.geometry} material={materials.Light} />
                    </group>
                  </group>
                  <group name="Line002" position={[-208, 3.17, 444.28]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_511" position={[0, 0.42, 342.059]}>
                      <mesh name="Line002_Light_0" geometry={nodes.Line002_Light_0.geometry} material={materials.Light} />
                    </group>
                  </group>
                  <group name="Rectangle002" position={[-208, 3, 456.807]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_514" position={[1.276, -1.877, 342.059]}>
                      <mesh name="Rectangle002_Chrome_0" geometry={nodes.Rectangle002_Chrome_0.geometry} material={materials.Chrome} />
                    </group>
                  </group>
                  <group name="Line003" position={[276.076, 3.17, 444.28]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_517" position={[0, 0.42, 342.059]}>
                      <mesh name="Line003_Light_0" geometry={nodes.Line003_Light_0.geometry} material={materials.Light} />
                    </group>
                  </group>
                  <group name="Rectangle003" position={[276.076, 3, 456.807]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_520" position={[1.276, -1.877, 342.059]}>
                      <mesh name="Rectangle003_Chrome_0" geometry={nodes.Rectangle003_Chrome_0.geometry} material={materials.Chrome} />
                    </group>
                  </group>
                  <group name="Line004" position={[276.076, 3.17, -414.291]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_523" position={[0, 0.42, 342.059]}>
                      <mesh name="Line004_Light_0" geometry={nodes.Line004_Light_0.geometry} material={materials.Light} />
                    </group>
                  </group>
                  <group name="VRayLight008" position={[436.5, 3.17, -416.827]} scale={[2.014, 1, 1]} />
                  <group name="VIFS098" position={[-170.5, -290, 1279]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_530" position={[-694.5, -2578, -9.5]}>
                      <mesh name="VIFS098_NCS_S_5005-Y50R_semiglos_0" geometry={nodes['VIFS098_NCS_S_5005-Y50R_semiglos_0'].geometry} material={materials['NCS_S_5005-Y50R_semiglos']} />
                    </group>
                  </group>
                  <group name="VIFS097" position={[-855.5, -269.5, 0]} rotation={[Math.PI / 2, -1.571, 0]}>
                    <group name="Object_533" position={[-30, -1299, -9.5]}>
                      <mesh name="VIFS097_NCS_S_5005-Y50R_semiglos_0" geometry={nodes['VIFS097_NCS_S_5005-Y50R_semiglos_0'].geometry} material={materials['NCS_S_5005-Y50R_semiglos']} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/wardrobe-7.glb')
