/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/wardrobe-4.glb --t 
Author: haihannah (https://sketchfab.com/haihannah)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wardrobe-acfae49ccfa64df3addbe37ab4919b85
Title: Wardrobe
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Box001_14_-_Polished_Aluminum_0']: THREE.Mesh
    ['Box001_15_-_Glossy_Plastic_0']: THREE.Mesh
    ['Object001_14_-_Polished_Aluminum_0']: THREE.Mesh
    ['Object003_14_-_Polished_Aluminum_0']: THREE.Mesh
    ['Object004_14_-_Polished_Aluminum_0']: THREE.Mesh
  }
  materials: {
    ['14_-_Polished_Aluminum']: THREE.MeshStandardMaterial
    ['15_-_Glossy_Plastic']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Wardrobe4(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/wardrobe-4.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-4.505, 62.459, 0]}>
        <mesh geometry={nodes['Box001_14_-_Polished_Aluminum_0'].geometry} material={materials['14_-_Polished_Aluminum']} />
        <mesh geometry={nodes['Box001_15_-_Glossy_Plastic_0'].geometry} material={materials['15_-_Glossy_Plastic']} />
      </group>
      <group position={[-52.377, 36.749, 35.999]}>
        <mesh geometry={nodes['Object001_14_-_Polished_Aluminum_0'].geometry} material={materials['14_-_Polished_Aluminum']} position={[47.873, 25.659, -50.538]} />
      </group>
      <group position={[-52.348, 21.006, 37.72]}>
        <mesh geometry={nodes['Object003_14_-_Polished_Aluminum_0'].geometry} material={materials['14_-_Polished_Aluminum']} position={[47.844, 9.915, -52.193]} />
      </group>
      <group position={[-52.377, 21.447, 44.096]}>
        <mesh geometry={nodes['Object004_14_-_Polished_Aluminum_0'].geometry} material={materials['14_-_Polished_Aluminum']} position={[47.873, 25.659, -50.538]} />
      </group>
    </group>
  )
}

useGLTF.preload('/wardrobe-4.glb')
